### PR TITLE
Update klaussilveira/gitter dependancy to 0.4.*

### PR DESCRIPTION
**Pull request by davidnewcomb**
You don't get a nice branch name ;)

### CODE REVIEW

**Comment by DannyvdSluijs** [comment]
Wouldn’t we need changes to the composer.lock as well? Otherwise we would still provide the release with 0.2 gitter.

I can create a new pull request later this week if needed.

**Comment by alehaa** [comment]
There's a [warning about incompatibility](https://travis-ci.org/klaussilveira/gitlist/jobs/396059141#L533):

```
PHP Strict standards:  Declaration of GitList\Git\Repository::getStatistics() should be compatible with Gitter\Repository::getStatistics() in /home/travis/build/klaussilveira/gitlist/src/Git/Repository.php on line 12
PHP Stack trace:
PHP   1. {main}() /home/travis/build/klaussilveira/gitlist/vendor/phpunit/phpunit/phpunit:0
PHP   2. PHPUnit_TextUI_Command::main() /home/travis/build/klaussilveira/gitlist/vendor/phpunit/phpunit/phpunit:52
PHP   3. PHPUnit_TextUI_Command->run() /home/travis/build/klaussilveira/gitlist/vendor/phpunit/phpunit/src/TextUI/Command.php:100
PHP   4. PHPUnit_TextUI_TestRunner->doRun() /home/travis/build/klaussilveira/gitlist/vendor/phpunit/phpunit/src/TextUI/Command.php:149
PHP   5. PHPUnit_Framework_TestSuite->run() /home/travis/build/klaussilveira/gitlist/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:440
PHP   6. PHPUnit_Framework_TestSuite->run() /home/travis/build/klaussilveira/gitlist/vendor/phpunit/phpunit/src/Framework/TestSuite.php:722
PHP   7. call_user_func:{/home/travis/build/klaussilveira/gitlist/vendor/phpunit/phpunit/src/Framework/TestSuite.php:672}() /home/travis/build/klaussilveira/gitlist/vendor/phpunit/phpunit/src/Framework/TestSuite.php:672
PHP   8. InterfaceTest::setUpBeforeClass() /home/travis/build/klaussilveira/gitlist/vendor/phpunit/phpunit/src/Framework/TestSuite.php:672
PHP   9. GitList\Git\Client->createRepository() /home/travis/build/klaussilveira/gitlist/tests/InterfaceTest.php:45
PHP  10. Composer\Autoload\ClassLoader->loadClass() /home/travis/build/klaussilveira/gitlist/tests/InterfaceTest.php:81
PHP  11. Composer\Autoload\includeFile() /home/travis/build/klaussilveira/gitlist/vendor/composer/ClassLoader.php:322
PHP  12. include() /home/travis/build/klaussilveira/gitlist/vendor/composer/ClassLoader.php:444
```

**Comment by davidnewcomb** [comment]
I have wound the composer.lock back to the same as `master`. The newer versions pulled in by upgrading to 0.4.0 are also probably 7.2+ compatible which breaks your tests which use php 5.4.
Only you can fix this because you need to decide your compatibility support level for this project.

**Comment by alehaa** [comment]
@klaussilveira can you take a look on this?

**Comment by siburny** [comment]
It looks like base Gitter class has this declaration: `public function getStatistics()` but derived class uses the following: `public function getStatistics($branch)`. Hense the error.

Reading through both functions it looks like they are not really the same: one gets stats for commits and the other for files. Best solution is to rename one of them to avoid collision.

**Pull request closed without merging**
