### PR TITLE
Dynamic package name

### PR DESCRIPTION
**Pull request by MacHoel**
Hi,

I am proposing this implementation to :
- Implement enhancement mentioned in issue #570 (also useful for testing => branch/tag always clearly visible in footer)
- Ease package generation with proper tar name (typically using build-package target)

I discovered about ant's build.xml and twig this week, so any critics welcome !

Cheers,
Hoel

### CODE REVIEW

**Comment by MacHoel** [comment]
CI now passes
Commits [4b0ccda](https://github.com/klaussilveira/gitlist/pull/861/commits/4b0ccdae5ca7da226dc74c1390c16ee3a07ad549) and [9785ed9](https://github.com/klaussilveira/gitlist/pull/861/commits/9785ed90e88109ff7395c9789138fd3481fa86a5) could be squashed before merge.

**Comment by alehaa** [comment]
Would there be an option to automatically update the download link in `gh-pages`, too?

**Comment by MacHoel** [comment]
I looked into gh-pages for the first time 10min ago, and realized there was something to do there ;)
I will look into it.

**Comment by MacHoel** [comment]
Hi Maintainers,

Anybody had a chance to review ?

**Comment by alehaa** [comment]
I think using the template variable in GitList is a good idea. However, I'm feeling uncomfortable with auto-pushing to the `gh-pages` branch. I had something like a generic URL to `latest` in mind ... What's your opinion on this @klaussilveira?

**Comment by klaussilveira** [comment]
I'm also not very fond of the auto-push to `gh-pages`. Can we keep just the dynamic build of "nightly builds"?

**Comment by MacHoel** [comment]
Just to put things in perspective : auto pushing happens only on tag event in master, which really means on release in this repo. And it happens on successful build in CI.
The chance to have a mistake then comes from the human, as usual I would say, human who can fix their mistake in master and gh-pages if it ever happens.

**Pull request closed without merging**
