### PR TITLE
Resolve #786: directory structure

### LINKED ISSUE #786: Option to show repositories in directories
This is a feature request.

On [my install](https://git.camilstaps.nl/), I currently have a directory structure like this:

```
<repository root>
  - archived
    - repo1.git
    - repo2.git
  - repo3.git
  - repo4.git
```

The list of repositories on the gitlist homepage looks like:

```
archived/repo1.git
archived/repo2.git
repo3.git
repo4.git
```

I would suggest giving the option (through `config.ini`) to have the repository browser reflect the directory structure. I.e., the homepage could look like this:

```
archived/
repo3.git
repo4.git
```

And clicking on `archived` would bring you to:

```
repo1.git
repo2.git
```

This would make it much easier to structure large sets of repositories.

### PR DESCRIPTION
**Pull request by camilstaps**
This is a proposal to implement #786. To see what it looks like with the bootstrap theme, see https://git.camilstaps.nl/. The `z-test` directory has many nested levels, one of which does not contain repositories but does contain a directory with a repository. For this, I had to remove the runtime exception 'There are no GIT repositories in ...'.

Note 1: this incorporates code from #788, which is then not needed any more (although you may want to merge that even if you disagree with things from here).  
Note 2: the makefiles for the themes throw errors for me, so I did not update the CSS.  
Note 3: there seems to be an issue with travis which causes it to sometime not download stuff.

### CODE REVIEW

**Comment by klaussilveira** [comment]
Which errors are you seeing with the `Makefile`?

**Comment by camilstaps** [comment]
@klaussilveira It cannot find `bootstrap.less` (this is unrelated to my changes, I'm probably missing some package?):

```
$ make
lessc --compress less/style.less > css/style.css
FileError: 'vendor/bootstrap/bootstrap.less' wasn't found. Tried - /tmp/gitlist/themes/bootstrap3/less/vendor/bootstrap/bootstrap.less,/tmp/gitlist/themes/bootstrap3/less/vendor/bootstrap/bootstrap.less,vendor/bootstrap/bootstrap.less in /tmp/gitlist/themes/bootstrap3/less/style.less
```

Since the CSS changes were minimal, to test I just copied the less to the old CSS and filled in the variables.

**Comment by camilstaps** [comment]
@klaussilveira could you have a look at this when you have time? I have used this for some time on my install now and have not encountered any oddities.

**Comment by klaussilveira** [comment]
I'm a little apprehensive because it's a major new feature that might add some bugs. We want to keep gitlist as stable as possible. But let's test and check the impact.

**Comment by camilstaps** [comment]
I have removed the `z-test` directory mentioned above from my server; I never meant to keep it around this long. The `archived` directory has one subdirectory (`botleagues`), which can still be used to see that things work with subdirectories. I have not experienced any problems so far.

**Comment by swus13** [comment]
Every kind of style is good, I only had plain html.
But I could just fix it with the statment:
    `lessc --compress less/bootstrap.less > css/style.css`

grafik

An icon I can't see.

As ideas for later, you can also display the number of subfolders, or something like that.

**Comment by camilstaps** [comment]
You're probably on the default theme then. It looks like this with the bootstrap theme (on [my install](https://git.camilstaps.nl)):

2018-10-11-104233_189x210

**Pull request closed without merging**
