### PR TITLE
Strip dot git

### PR DESCRIPTION
**Pull request by MacHoel**
Hi,

Anybody else bothered by the display of the .git extension of their bare repositories ?

### CODE REVIEW

**Comment by alehaa** [comment]
As this is optional, there shouldn't be problems when merging this PR. Did you check, if other components required further changes for generating the correct URLs?

**Comment by MacHoel** [comment]
Hi, my analysis and tests at the time showed this was the centralized way to implement it, so no other modifications needed.
Any concern for merging ?

**Comment by alehaa** [comment]
@klaussilveira do you have any concerns on this PR?

**Comment by klaussilveira** [comment]
Nope, I think it is in good shape.

**Pull request merged**
