### PR TITLE
Add tab to draw a graphical representation of the commit history

### PR DESCRIPTION
**Pull request by guiyomh**
Add tab to draw a graphical representation of the commit history

### CODE REVIEW

**Comment by chauffer** [comment]
Your graph does not render correctly with the bootstrap3 theme.
1000_2015-01-18_13-00-55_6kxxoygyxlbyesrr3uso4zr9eucu5ju3vzcb

**Comment by jniggemann** [comment]
FYI: I found no issues with 0.5.0 and bootstrap3

**Comment by klaussilveira** [comment]
@chauffer, which browser did you test it on?

**Comment by JBlond** [comment]
:+1: for this feature

**Pull request merged**
