### PR TITLE
Fixing TreeGraphController.php position

### PR DESCRIPTION
**Pull request by teodoropiccinni**
After launching "composer update", editing config.ini and solved permissions issues, I still got blank page. Solved with that edit moved TreeGraphController to src/Controller folder

### CODE REVIEW

**Comment by Hologos** [comment]
There are several pull requests that already fixes this. Sadly, the OP currently does not maintain the project.

**Comment by klaussilveira** [comment]
We have other contributors working in the project, but none of them seem to have enough time to dedicate to it.

**Comment by teodoropiccinni** [comment]
I can write a WiKi in order to make installation easier and fix that issue. This is not much, but it could help your work...

**Comment by Hologos** [comment]
This PR can be closed because it was fixed with #682.

**Pull request closed without merging**
